name: Environment Vars in GitHub
on:
  push:
    branches: dev
  workflow_dispatch:

env:
  ENCRYPTION_SECRET: ${{ vars.NEXT_PUBLIC_ENCRYPTION_SECRET }}
  region: ${{ vars.REGION }}
  URL_BACKEND_ONE: ${{ secrets.NEXT_PUBLIC_BASE_URL_BACKEND_ONE_PROD }}
  IMAGE_PATH_URL: ${{ secrets.NEXT_PUBLIC_IMAGE_PATH_URL }}
  PUBLIC_SECRET_KEY: ${{ secrets.NEXT_PUBLIC_SECRET_KEY }}
    
jobs:
  build:
    runs-on: ubuntu-latest   
    environment: ${{ GITHUB_REF_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build and push docker image
        run: |
          echo "NEXT_PUBLIC_SECRET_KEY=${{ env.PUBLIC_SECRET_KEY }}" >> .env
          echo "NEXT_PUBLIC_BASE_URL_BACKEND_ONE=${{ env.URL_BACKEND_ONE_PROD }}" >> .env
          echo "NEXT_PUBLIC_IMAGE_PATH_URL=${{ env.IMAGE_PATH_URL }}" >> .env
          echo "NEXT_PUBLIC_ENCRYPTION_SECRET=${{ env.ENCRYPTION_SECRET }}" >> .env

          export CR_PAT=${{ secrets.TOKEN }}
          echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
          docker pull ghcr.io/${GITHUB_REPOSITORY}:production || true
          docker build --tag ghcr.io/${GITHUB_REPOSITORY}:production .
          docker push ghcr.io/${GITHUB_REPOSITORY}:production



      
      