name: Package on GitHub
on:
  push:
    branches: dev
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest   
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build and push docker image
        run: |
          echo "NEXT_PUBLIC_SECRET_KEY=${{ secrets.NEXT_PUBLIC_SECRET_KEY }}" >> .env
          echo "NEXT_PUBLIC_BASE_URL_BACKEND_ONE=${{ secrets.NEXT_PUBLIC_BASE_URL_BACKEND_ONE_PROD }}" >> .env
          echo "NEXT_PUBLIC_IMAGE_PATH_URL=${{ secrets.NEXT_PUBLIC_IMAGE_PATH_URL }}" >> .env
          echo "NEXT_PUBLIC_ENCRYPTION_SECRET=${{ secrets.NEXT_PUBLIC_ENCRYPTION_SECRET }}" >> .env

          export CR_PAT=${{ secrets.TOKEN }}
          echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
          docker pull ghcr.io/${GITHUB_REPOSITORY}:production || true
          docker build --tag ghcr.io/${GITHUB_REPOSITORY}:production .
          docker push ghcr.io/${GITHUB_REPOSITORY}:production
           
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: SCP and copy code to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: 'ubuntu'
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: 'docker-compose-prod.yml'
          target: '~/web-production'
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: 'ubuntu'
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd ~/web-production
            cp docker-compose-prod.yml docker-compose.yml
            rm docker-compose-prod.yml
            export password=${{ secrets.TOKEN }}
            export username=${{ github.actor }}
            export CR_PAT=${{ secrets.TOKEN }}
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.TOKEN }}
            docker-compose down
            docker image rm ghcr.io/revolvebypreethi/website:production
            docker-compose up -d
