name: Web Staging
on:
  push:
    branches: [dev, main]
  workflow_dispatch:
    
env: 

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest   
    environment: dev  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: GCP Login
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}