name: Web Staging
on:
  push:
    branches: [dev, main]
    paths: "src/**"
  workflow_dispatch:
    
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest   
    environment: dev  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: GCP Login
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
      
      - name: GCloud Config
        run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev

      - name: build and push docker image
        run: |
          echo "NEXT_PUBLIC_SECRET_KEY=${{ vars.NEXT_PUBLIC_SECRET_KEY }}" >> .env
          echo "NEXT_PUBLIC_BASE_URL_BACKEND_ONE=${{ vars.NEXT_PUBLIC_BASE_URL_BACKEND_ONE_PROD }}" >> .env
          echo "NEXT_PUBLIC_IMAGE_PATH_URL=${{ vars.NEXT_PUBLIC_IMAGE_PATH_URL }}" >> .env
          echo "NEXT_PUBLIC_ENCRYPTION_SECRET=${{ vars.NEXT_PUBLIC_ENCRYPTION_SECRET }}" >> .env

          docker pull ${{ vars.GAR_LOCATION }}/${{ github.repository }}:dev || true
          docker build --tag ${{ vars.GAR_LOCATION }}/${{ github.repository }}:dev .
          docker push ${{ vars.GAR_LOCATION }}/${{ github.repository }}:dev
